version: '3'

networks:
  mangata:
    name: mangata
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  node_alice:
    image: mangatasolutions/mangata-node
    container_name: mangata-node
    entrypoint: ./node --dev --alice --validator --unsafe-ws-external --rpc-cors=all -lruntime=debug --node-key=0000000000000000000000000000000000000000000000000000000000000001 --prometheus-port 9716 --prometheus-external
    ports:
      - '30333:30333'
      - '9933:9933'
      - '9944:9944'
      - '9716:9716'
    networks:
      mangata:
        ipv4_address: 172.18.0.10

  node_bob:
    image: mangatasolutions/mangata-node
    container_name: bob
    entrypoint: ./node --dev --bob --unsafe-ws-external --rpc-cors=all -lruntime=debug --bootnodes='/ip4/172.18.0.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp' --prometheus-port 9717 --prometheus-external
    depends_on:
      - node_alice
    ports:
      - '30335:30333'
      - '9935:9933'
      - '9946:9944'
      - '9717:9717'
    networks:
      mangata:
        ipv4_address: 172.18.0.2

  node_charlie:
    image: mangatasolutions/mangata-node
    container_name: charlie
    entrypoint: ./node --dev --charlie --unsafe-ws-external --rpc-cors=all -lruntime=debug --bootnodes='/ip4/172.18.0.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp' --prometheus-port 9718 --prometheus-external
    depends_on:
      - node_alice
    ports:
      - '30337:30333'
      - '9937:9933'
      - '9948:9944'
      - '9718:9718'
    networks:
      mangata:
        ipv4_address: 172.18.0.3

  node_dave:
    image: mangatasolutions/mangata-node
    container_name: dave
    entrypoint: ./node --dev --dave --unsafe-ws-external --rpc-cors=all -lruntime=debug --bootnodes='/ip4/172.18.0.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp' --prometheus-port 9718 --prometheus-external
    depends_on:
      - node_alice
    ports:
      - '30339:30333'
      - '9939:9933'
      - '9950:9944'
    networks:
      mangata:
        ipv4_address: 172.18.0.4

  node_eve:
    image: mangatasolutions/mangata-node
    container_name: eve
    entrypoint: ./node --dev --eve --unsafe-ws-external --rpc-cors=all -lruntime=debug --bootnodes='/ip4/172.18.0.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp' --prometheus-port 9718 --prometheus-external
    depends_on:
      - node_alice
    ports:
      - '30341:30333'
      - '9941:9933'
      - '9952:9944'
    networks:
      mangata:
        ipv4_address: 172.18.0.5

  node_ferdie:
    image: mangatasolutions/mangata-node
    container_name: ferdie
    entrypoint: ./node --dev --ferdie --unsafe-ws-external --rpc-cors=all -lruntime=debug --bootnodes='/ip4/172.18.0.10/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp' --prometheus-port 9718 --prometheus-external
    depends_on:
      - node_alice
    ports:
      - '30343:30333'
      - '9943:9933'
      - '9954:9944'
    networks:
      mangata:
        ipv4_address: 172.18.0.6
